version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  create-update:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - kubernetes/install-kubectl
      
workflows:
  build-workflow:
    jobs:
      - create-update
    
