version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  create-update:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - kubernetes/install
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: tests/nginx-deployment/deployment.yaml
          resource-name: deployment/nginx-deployment
          show-kubectl-command: true
workflows:
  build-workflow:
    jobs:
      - create-update
    
